id: IE99C2402
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T15:40:58+00:00'
last_modified: '2022-06-08T11:18:24.945879+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24773
  title: བསམ་པ་ཆུ་ལྟར་བཞུར་བའི་སྒྲ་དབྱངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    C9BA:
      image_group_id: I1KG24775
      title: ''
      total_pages: 799
      order: 1
      base_file: C9BA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
