id: P009475
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG24773
  title: བསམ་པ་ཆུ་ལྟར་བཞུར་བའི་སྒྲ་དབྱངས།
  author: ''
  volumes:
    87272fa5adce4f55b4b9856624d24a72:
      image_group_id: I1KG24775
      title: ''
      volume_number: 1
      total_pages: 799
      base_file: v001.txt
